# Generated by Django 3.2.13 on 2022-07-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donateitem',
            options={'ordering': ('created',)},
        ),
    ]
