# Generated by Django 3.2.13 on 2022-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220805_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBanks',
            fields=[
                ('active', models.BooleanField()),
                ('code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('createdAt', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('gateway', models.CharField(max_length=300, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField()),
                ('longcode', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=300)),
                ('pay_with_bank', models.BooleanField()),
                ('slug', models.SlugField()),
                ('type', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
