# Generated by Django 3.2.13 on 2022-09-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_availablebanks_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountnumber',
            name='account_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountnumber',
            name='account_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountnumber',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.availablebanks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountnumber',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_numbers', related_query_name='account_numbers', to='accounts.user'),
            preserve_default=False,
        ),
    ]
