# Generated by Django 3.2.13 on 2022-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220906_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablebanks',
            options={'ordering': ('id',), 'verbose_name_plural': 'Available Banks'},
        ),
        migrations.AlterField(
            model_name='useraccountnumber',
            name='account_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
