# Generated by Django 3.2.13 on 2022-09-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220907_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablebanks',
            options={'ordering': ('id',), 'verbose_name': 'Banks', 'verbose_name_plural': 'Available Banks'},
        ),
        migrations.AlterModelOptions(
            name='useraccountnumber',
            options={'verbose_name': 'Account detail', 'verbose_name_plural': 'Account details'},
        ),
    ]
