# Generated by Django 3.2.13 on 2022-07-08 07:06

from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchdocument',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='file',
            field=models.FileField(upload_to=research.models.upload_and_rename_research_document),
        ),
    ]
