# Generated by Django 3.2.13 on 2022-07-08 21:20

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20220708_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocument',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'id']),
        ),
    ]
