# Generated by Django 3.2.13 on 2022-08-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_researchdocument_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchdocument',
            options={'ordering': ['name']},
        ),
    ]
