# Generated by Django 3.2.13 on 2022-08-21 22:10

import cloudinary_storage.storage
from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_researchdocument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocument',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=research.models.upload_and_rename_research_document),
        ),
    ]
