# Generated by Django 3.2.13 on 2022-09-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchdocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchdocument',
            options={'ordering': ['created_on']},
        ),
    ]
