# Generated by Django 3.2.13 on 2022-07-11 08:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmProdudeOrder',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('unit', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=11)),
                ('produce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_order', related_query_name='farm_order', to='farms.farmproduce')),
            ],
        ),
    ]
