# Generated by Django 3.2.13 on 2022-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproduce',
            name='unit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
