# Generated by Django 3.2.13 on 2022-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farmprodudeorder_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmprodudeorder',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
