# Generated by Django 3.2.13 on 2022-08-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_alter_farmprodudeorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproduce',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
