# Generated by Django 3.2.13 on 2022-08-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_alter_farmprodudeorder_produce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmprodudeorder',
            name='produce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_order', related_query_name='farm_order', to='farms.farmproduce'),
        ),
    ]
