# Generated by Django 3.2.13 on 2022-09-08 10:00

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_alter_farmprodudeorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprodudeorder',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
